"""Constants for the language-modeling exercise."""

LANGUAGE_VOCABULARY_SIZE = 300000
ROUND_DIGITS_CNT = 5
UNSEEN_WORD = "unseen-word"
SMOOTHING_FACTOR_MIN = 0.0
SMOOTHING_FACTOR_MAX = 2.0
SMOOTHING_FACTOR_STEP = 0.01
